version: '3.0'

services:

    comic_node:
        build: ../ # using layer cache
        container_name: comic-node-app
        working_dir: /app
        volumes:
            - ../../:/app:cached
            - ../supervisor.conf:/etc/supervisor/conf.d/node_comic.conf:cached
            - ../ini.sh:/usr/src/ini.sh:cached
            - /tmp/comic_node:/tmp/comic:cached
        ports:
            - 7070:7070
        environment:
            TZ: Asia/Shanghai
            NODE_ENV: production
            TERM: xterm
            NODE_OPTIONS: '--openssl-legacy-provider'
        networks:
            default:
                ipv4_address: 172.28.0.2
        # 生产开启这个
        command: bash -c "bash /usr/src/ini.sh && tail -f "
        # 部署资源限制
        deploy:
            replicas: 1  # 指定部署数量
            resources:
                limits: # cpu最大使用数
                    cpus: '0.8' # 该服务cpu资源可用百分比，单个cpu打满就是 100%, 这里的 1.0 就是 100% 的 意思
                    memory: 1000M # 主要是编译耗内存：特别是www服务的编译 峰值700~800M，如果只编译 task服务 只需要200M 就够用

networks:
    default:
        external:
            name: network_unix
